name: Build

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
          #- macos-latest # = macos-12
          #- macos-14     # M1

jobs:
  build-cpp-interface:
    uses: alexander-g/traininglib/.github/workflows/build.yml@main
    with:
      os: ${{ inputs.os }}
      tests: false

  build-ui:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Debug
        run: |
          ls -R

      - name: Build UI
        run: |
          git submodule update
          bash -xe ./build.sh
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: |
            main
            main.exe
            static/*
            models/models.json
          retention-days: 1
  
  package:
    runs-on: ${{ inputs.os }}
    needs:   [build-cpp-interface, build-ui]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - run: ls -R

      - uses: actions/checkout@v4
        with:
          path:       ./repo/
          submodules: 'recursive'

      - name: re-order
        run: |
          bash -xe repo/.github/workflows/scripts/reorder-for-package-${{ inputs.os }}.sh
      
      - name: Zip
        uses: actions/upload-artifact@v4
        with:
          name: packaged
          path: ./package/*
          retention-days: 1
