name: Build

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
          #- macos-latest

jobs:
  build-cpp-interface:
    uses: alexander-g/traininglib/.github/workflows/build.yml@main
    with:
      os: ${{ inputs.os }}
      tests: false

  build-ui:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Debug
        run: |
          ls -R

      - name: Build UI
        run: |
          git submodule update
          bash -xe ./build.sh
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: ui-build
          path: |
            main
            main.exe
            static/*
            models/models.json
          retention-days: 1
  
  package:
    runs-on: ${{ inputs.os }}
    needs:   [build-cpp-interface, build-ui]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - run: ls -R

      - name: re-order
        run: |
          bash -c 'find ./ -name static -exec cp -r {} ./static \;'
          mkdir -p ./assets
          bash -c 'find ./ -name TSinterface.dll    -exec cp {} ./assets/ \;'
          bash -c 'find ./ -name libTSinterface.so  -exec cp {} ./assets/ \;'
          bash -c 'find ./ -name main      -exec cp {} ./assets/ \;'
          bash -c 'find ./ -name main.exe  -exec cp {} ./assets/ \;'
          mkdir -p models
          bash -c 'find ./ -name models.json  -exec cp {} ./models/ \;'
          rm -r artifacts
          bash -c 'echo "SET ROOT_PATH=%~dp0" > main.bat'
          bash -c 'echo "assets\main.exe %*" >> main.bat'
          bash -c 'echo "pause"              >> main.bat'
      
      - name: Zip
        uses: actions/upload-artifact@v4
        with:
          name: packaged
          path: ./*
          retention-days: 1

    