name: Build


on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          #- macos-latest


jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout traininglib
        uses: actions/checkout@v4
        with:
          repository: alexander-g/traininglib
          path: traininglib

      - name: Build C++ interface
        run: |
          cd traininglib
          gh workflow run tests.yml -f os=${{ inputs.os }}
          cd ..
          mkdir assets
          cp traininglib/cpp/build/*.so ./assets/
          cp traininglib/cpp/build/**/TSinterface.dll ./assets/
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build UI
        run: |
          bash ./build.sh
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            main
          retention-days: 1